<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Product;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Napa',
                'genericName' => 'Paracetamol',
                'brand_id' => 1,
                'category_id' => 1,
                'purchase_price' => 3,
                'price' => 5,
                'stock' => 100,
                'manufacture_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Used for fever and mild pain relief',
            ],
            [
                'name' => 'Nurofen',
                'genericName' => 'Ibuprofen',
                'brand_id' => 2,
                'category_id' => 1,
                'purchase_price' => 1,
                'price' => 2,
                'stock' => 80,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYears(2)->format('Y-m-d'),
                'description' => 'Pain, inflammation, and fever relief',
            ],
            [
                'name' => 'Amoxil',
                'genericName' => 'Amoxicillin',
                'brand_id' => 3,
                'category_id' => 2,
                'purchase_price' => 3,
                'price' => 5,
                'stock' => 50,
                'manufacture_date' => Carbon::now()->subMonth()->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Antibiotic for bacterial infections',
            ],
            [
                'name' => 'Azimax',
                'genericName' => 'Azithromycin',
                'brand_id' => 3,
                'category_id' => 2,
                'purchase_price' => 15,
                'price' => 20,
                'stock' => 40,
                'manufacture_date' => Carbon::now()->subMonths(4)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addMonths(20)->format('Y-m-d'),
                'description' => 'Used to treat various infections',
            ],
            [
                'name' => 'Glucophage',
                'genericName' => 'Metformin',
                'brand_id' => 4,
                'category_id' => 3,
                'purchase_price' => 2,
                'price' => 3,
                'stock' => 70,
                'manufacture_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYears(2)->format('Y-m-d'),
                'description' => 'Used for Type 2 diabetes management',
            ],
            [
                'name' => 'Why',
                'genericName' => 'Recent',
                'brand_id' => 3,
                'category_id' => 1,
                'purchase_price' => 14.5,
                'price' => 19.70,
                'stock' => 140,
                'manufacture_date' => '2025-06-19',
                'expiry_date' => '2027-01-16',
                'description' => 'Everybody wind because new throw box read.',
            ],
            [
                'name' => 'See',
                'genericName' => 'Wife',
                'brand_id' => 1,
                'category_id' => 2,
                'purchase_price' => 21.5,
                'price' => 28.58,
                'stock' => 170,
                'manufacture_date' => '2025-05-25',
                'expiry_date' => '2026-06-25',
                'description' => 'Artist church professor but interview see hard word.',
            ],
            [
                'name' => 'Ask',
                'genericName' => 'Detail',
                'brand_id' => 2,
                'category_id' => 4,
                'purchase_price' => 30.2,
                'price' => 40.12,
                'stock' => 33,
                'manufacture_date' => '2025-02-25',
                'expiry_date' => '2026-05-17',
                'description' => 'Less time nothing reflect any.',
            ],
            [
                'name' => 'Admit',
                'genericName' => 'Research',
                'brand_id' => 5,
                'category_id' => 2,
                'purchase_price' => 30.1,
                'price' => 43.02,
                'stock' => 148,
                'manufacture_date' => '2025-05-13',
                'expiry_date' => '2026-06-19',
                'description' => 'High tough nation they actually.',
            ],
            [
                'name' => 'Human',
                'genericName' => 'Painting',
                'brand_id' => 2,
                'category_id' => 2,
                'purchase_price' => 35.4,
                'price' => 41.28,
                'stock' => 75,
                'manufacture_date' => '2025-01-25',
                'expiry_date' => '2026-10-17',
                'description' => 'Challenge either case fill idea receive.',
            ],
            [
                'name' => 'Flagyl',
                'genericName' => 'Metronidazole',
                'brand_id' => 1,
                'category_id' => 1,
                'purchase_price' => 6,
                'price' => 10,
                'stock' => 100,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Used to treat bacterial infections.',
            ],
            [
                'name' => 'Nexium',
                'genericName' => 'Esomeprazole',
                'brand_id' => 2,
                'category_id' => 2,
                'purchase_price' => 10,
                'price' => 15,
                'stock' => 80,
                'manufacture_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Used to reduce stomach acid.',
            ],
            [
                'name' => 'Advil',
                'genericName' => 'Ibuprofen',
                'brand_id' => 3,
                'category_id' => 1,
                'purchase_price' => 5,
                'price' => 8,
                'stock' => 120,
                'manufacture_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Pain and fever relief.',
            ],
            [
                'name' => 'Tylenol',
                'genericName' => 'Paracetamol',
                'brand_id' => 1,
                'category_id' => 1,
                'purchase_price' => 3,
                'price' => 5,
                'stock' => 150,
                'manufacture_date' => Carbon::now()->subMonths(4)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Fever and mild pain relief.',
            ],
            [
                'name' => 'Zithromax',
                'genericName' => 'Azithromycin',
                'brand_id' => 4,
                'category_id' => 2,
                'purchase_price' => 15,
                'price' => 20,
                'stock' => 60,
                'manufacture_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Antibiotic for infections.',
            ],
            [
                'name' => 'Ventolin',
                'genericName' => 'Salbutamol',
                'brand_id' => 5,
                'category_id' => 3,
                'purchase_price' => 65,
                'price' => 90,
                'stock' => 40,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(3)->format('Y-m-d'),
                'description' => 'Used to relieve asthma symptoms.',
            ],
            [
                'name' => 'Claritin',
                'genericName' => 'Loratadine',
                'brand_id' => 3,
                'category_id' => 1,
                'purchase_price' => 4.5,
                'price' => 7,
                'stock' => 110,
                'manufacture_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Non-drowsy allergy relief.',
            ],
            [
                'name' => 'Augmentin',
                'genericName' => 'Amoxicillin + Clavulanic Acid',
                'brand_id' => 4,
                'category_id' => 2,
                'purchase_price' => 17,
                'price' => 25,
                'stock' => 70,
                'manufacture_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Broad-spectrum antibiotic.',
            ],
            [
                'name' => 'Prozac',
                'genericName' => 'Fluoxetine',
                'brand_id' => 1,
                'category_id' => 1,
                'purchase_price' => 12,
                'price' => 18,
                'stock' => 55,
                'manufacture_date' => Carbon::now()->subMonths(4)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(3)->format('Y-m-d'),
                'description' => 'Used to treat depression.',
            ],
            [
                'name' => 'Lipitor',
                'genericName' => 'Atorvastatin',
                'brand_id' => 2,
                'category_id' => 1,
                'purchase_price' => 15,
                'price' => 22,
                'stock' => 75,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Used to lower cholesterol.',
            ],
            [
                'name' => 'Xanax',
                'genericName' => 'Alprazolam',
                'brand_id' => 3,
                'category_id' => 1,
                'purchase_price' => 20,
                'price' => 30,
                'stock' => 45,
                'manufacture_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Used for anxiety disorders.',
            ],
            [
                'name' => 'Lasix',
                'genericName' => 'Furosemide',
                'brand_id' => 1,
                'category_id' => 1,
                'purchase_price' => 10,
                'price' => 12,
                'stock' => 90,
                'manufacture_date' => Carbon::now()->subMonths(5)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Diuretic for fluid retention.',
            ],
            [
                'name' => 'Synthroid',
                'genericName' => 'Levothyroxine',
                'brand_id' => 2,
                'category_id' => 1,
                'purchase_price' => 13,
                'price' => 17,
                'stock' => 60,
                'manufacture_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(3)->format('Y-m-d'),
                'description' => 'Used for thyroid hormone replacement.',
            ],
            [
                'name' => 'Coumadin',
                'genericName' => 'Warfarin',
                'brand_id' => 3,
                'category_id' => 1,
                'purchase_price' => 11,
                'price' => 20,
                'stock' => 50,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Blood thinner to prevent clots.',
            ],
            [
                'name' => 'Ambien',
                'genericName' => 'Zolpidem',
                'brand_id' => 4,
                'category_id' => 1,
                'purchase_price' => 14,
                'price' => 25,
                'stock' => 40,
                'manufacture_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Used for short-term insomnia.',
            ],
            [
                'name' => 'Diflucan',
                'genericName' => 'Fluconazole',
                'brand_id' => 5,
                'category_id' => 2,
                'purchase_price' => 21,
                'price' => 30,
                'stock' => 70,
                'manufacture_date' => Carbon::now()->subMonths(4)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Antifungal medication.',
            ],
            [
                'name' => 'Motrin',
                'genericName' => 'Ibuprofen',
                'brand_id' => 1,
                'category_id' => 1,
                'purchase_price' => 5,
                'price' => 9,
                'stock' => 130,
                'manufacture_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear()->format('Y-m-d'),
                'description' => 'Pain relief and anti-inflammatory.',
            ],
            [
                'name' => 'Plavix',
                'genericName' => 'Clopidogrel',
                'brand_id' => 2,
                'category_id' => 1,
                'purchase_price' => 23,
                'price' => 28,
                'stock' => 60,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(3)->format('Y-m-d'),
                'description' => 'Prevents blood clots.',
            ],
            [
                'name' => 'Zoloft',
                'genericName' => 'Sertraline',
                'brand_id' => 3,
                'category_id' => 1,
                'purchase_price' => 15,
                'price' => 22,
                'stock' => 50,
                'manufacture_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Used for depression and anxiety.',
            ],
            [
                'name' => 'Keflex',
                'genericName' => 'Cephalexin',
                'brand_id' => 4,
                'category_id' => 2,
                'purchase_price' => 13,
                'price' => 18,
                'stock' => 80,
                'manufacture_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'expiry_date' => Carbon::now()->addYear(2)->format('Y-m-d'),
                'description' => 'Antibiotic for infections.',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
